# planners:
planners:
  - name: ExperimentalPlanner
    type: mbf_experimental_core/ExperimentalPlanner

controllers:
  - name: ExperimentalController
    type: mbf_experimental_core/ExperimentalController

recovery_behaviors:
  - name: ExperimentalRecovery
    type: mbf_experimental_core/ExperimentalRecovery
